"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 23:17:21.723166
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.CheckConstraint("actor_type IN ('patient', 'staff', 'system')", name='ck_audit_log_actor_type'),
    sa.CheckConstraint('length(action) > 0', name='ck_audit_log_action_nonempty'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_log_actor', ['actor_type', 'actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_audit_log_patient_ts', ['patient_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('caregiver_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caregiver_accounts'))
    )
    with op.batch_alter_table('caregiver_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caregiver_accounts_email'), ['email'], unique=True)

    op.create_table('login_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IN ('patient','staff')", name='ck_loginfail_account_type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_failures'))
    )
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.create_index('ix_loginfail_email_ts', ['account_type', 'email', 'ts'], unique=False)
        batch_op.create_index('ix_loginfail_ip_ts', ['ip', 'ts'], unique=False)

    op.create_table('notification_prefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("recipient_type IN ('patient', 'staff')", name='ck_notification_prefs_recipient_type'),
    sa.CheckConstraint("recipient_type IN ('patient','staff')", name='ck_notif_pref_type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_prefs')),
    sa.UniqueConstraint('recipient_type', 'recipient_id', 'kind', name='uq_notif_pref')
    )
    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_prefs_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("recipient_type IN ('patient', 'staff')", name='ck_notifications_recipient_type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index('ix_notifications_recipient_ts', ['recipient_type', 'recipient_id', 'ts'], unique=False)
        batch_op.create_index('ix_notifications_recipient_unread', ['recipient_type', 'recipient_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_ts'), ['ts'], unique=False)

    op.create_table('otp_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=200), nullable=False),
    sa.Column('challenge_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.CheckConstraint("account_type IN ('patient','staff')", name='ck_otp_account_type'),
    sa.CheckConstraint("purpose IN ('signup','login','reset','email_change')", name='ck_otp_purpose'),
    sa.CheckConstraint('attempts >= 0 AND max_attempts > 0', name='ck_otp_attempts'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_challenge_hash'), ['challenge_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_email'), ['email'], unique=False)
        batch_op.create_index('ix_otp_ip_created', ['ip', 'created_at'], unique=False)
        batch_op.create_index('ix_otp_key_created', ['account_type', 'email', 'purpose', 'created_at'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('preferred_name', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('pronouns', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_note', sa.String(length=300), nullable=True),
    sa.Column('allergy_status', sa.String(length=30), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("allergy_status IN ('unknown', 'has_allergies', 'no_known_allergies')", name='ck_patients_allergy_status'),
    sa.CheckConstraint("verification_status IN ('unverified', 'pending', 'verified')", name='ck_patients_verification_status'),
    sa.CheckConstraint('length(email) > 2', name='ck_patients_email_nonempty'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_dob', ['dob'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=True)
        batch_op.create_index('ix_patients_legal_name', ['legal_name'], unique=False)

    op.create_table('pending_signups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IN ('patient','staff')", name='ck_pending_account_type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_signups')),
    sa.UniqueConstraint('account_type', 'email', name='uq_pending_signup_email')
    )
    with op.batch_alter_table('pending_signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_signups_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_signups_expires_at'), ['expires_at'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('availability_json', sa.Text(), nullable=True),
    sa.Column('cost_estimates_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index('ix_providers_name', ['name'], unique=False)

    op.create_table('reminder_log',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_reminder_log'))
    )
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_log_created_at'), ['created_at'], unique=False)

    op.create_table('share_token_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_token_attempts'))
    )
    with op.batch_alter_table('share_token_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_share_token_attempts_key_ts', ['key', 'ts'], unique=False)

    op.create_table('trusted_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IN ('patient','staff')", name='ck_trusted_account_type'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_devices')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_trusted_devices_token_hash'))
    )
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.create_index('ix_trusted_account', ['account_type', 'account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trusted_devices_expires_at'), ['expires_at'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('intake_json', sa.Text(), nullable=False),
    sa.Column('contact_json', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.String(length=60), nullable=True),
    sa.Column('staff_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'requested', 'booked', 'rescheduled', 'cancelled', 'declined')", name='ck_appointments_status'),
    sa.CheckConstraint("status IN ('draft','requested','booked','rescheduled','cancelled','declined')", name='ck_appt_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_appointments_provider_id_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index('ix_appointments_provider_status', ['provider_id', 'status'], unique=False)
        batch_op.create_index('ix_appointments_scheduled_for', ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_updated_at'), ['updated_at'], unique=False)

    op.create_table('caregiver_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('caregiver_id', sa.String(length=36), nullable=True),
    sa.Column('invite_email', sa.String(length=254), nullable=False),
    sa.Column('invite_name', sa.String(length=200), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('invite_token_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('record_categories_json', sa.Text(), nullable=False),
    sa.Column('manage_appointments', sa.Boolean(), nullable=False),
    sa.Column('manage_bills', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('invited','active','revoked','declined')", name='ck_caregiver_link_status'),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver_accounts.id'], name=op.f('fk_caregiver_links_caregiver_id_caregiver_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_caregiver_links_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caregiver_links')),
    sa.UniqueConstraint('invite_token_hash', name=op.f('uq_caregiver_links_invite_token_hash'))
    )
    with op.batch_alter_table('caregiver_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caregiver_links_caregiver_id'), ['caregiver_id'], unique=False)
        batch_op.create_index('ix_caregiver_links_email', ['invite_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_caregiver_links_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_caregiver_links_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_caregiver_links_patient_status', ['patient_id', 'status'], unique=False)

    op.create_table('caregiver_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('caregiver_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver_accounts.id'], name=op.f('fk_caregiver_sessions_caregiver_id_caregiver_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_caregiver_sessions'))
    )
    with op.batch_alter_table('caregiver_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caregiver_sessions_caregiver_id'), ['caregiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_caregiver_sessions_expires_at'), ['expires_at'], unique=False)

    op.create_table('connected_apps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('app_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_connected_apps_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connected_apps'))
    )
    with op.batch_alter_table('connected_apps', schema=None) as batch_op:
        batch_op.create_index('ix_connected_apps_patient', ['patient_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_connected_apps_patient_id'), ['patient_id'], unique=False)

    op.create_table('deletion_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('earliest_completion_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','cancelled','completed')", name='ck_deletion_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_deletion_requests_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_requests'))
    )
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletion_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_deletion_requests_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_requests_status'), ['status'], unique=False)

    op.create_table('dependent_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guardian_patient_id', sa.String(length=36), nullable=False),
    sa.Column('dependent_patient_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dependent_patient_id'], ['patients.id'], name=op.f('fk_dependent_profiles_dependent_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_patient_id'], ['patients.id'], name=op.f('fk_dependent_profiles_guardian_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependent_profiles')),
    sa.UniqueConstraint('dependent_patient_id', name='uq_dependent_patient')
    )
    with op.batch_alter_table('dependent_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependent_profiles_guardian_patient_id'), ['guardian_patient_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('uploaded_by_type', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.CheckConstraint("source IN ('patient_uploaded','clinician_provided')", name='ck_documents_source'),
    sa.CheckConstraint("uploaded_by_type IN ('patient', 'staff', 'system')", name='ck_documents_uploaded_by_type'),
    sa.CheckConstraint('length(name) >= 1', name='ck_documents_name_nonempty'),
    sa.CheckConstraint('length(sha256) = 64', name='ck_documents_sha256_len'),
    sa.CheckConstraint('size_bytes >= 0 AND size_bytes <= 15728640', name='ck_documents_size_bytes'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_documents_size'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_documents_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_mime_type'), ['mime_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_name'), ['name'], unique=False)
        batch_op.create_index('ix_documents_patient_created', ['patient_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index('uq_documents_patient_sha256_live', ['patient_id', 'sha256'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('uq_documents_patient_sha_active', ['patient_id', 'sha256'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))

    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('authorized_to_access_records', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_emergency_contacts_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_contacts'))
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_contacts_patient_id'), ['patient_id'], unique=False)

    op.create_table('med_allergies',
    sa.Column('substance', sa.String(length=200), nullable=False),
    sa.Column('substance_key', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('reaction', sa.String(length=300), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('onset', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='patient_entered', nullable=False),
    sa.Column('confirmed_by', sa.String(length=200), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('drug','food','environmental','other','unknown')", name='ck_med_allergies_category'),
    sa.CheckConstraint("severity IN ('mild','moderate','severe','unknown')", name='ck_med_allergies_severity'),
    sa.CheckConstraint("source IN ('patient_entered','clinician_confirmed')", name='ck_med_allergies_source'),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_med_allergies_status'),
    sa.CheckConstraint('length(substance) >= 1', name='ck_med_allergies_substance'),
    sa.CheckConstraint('onset IS NULL OR length(onset) IN (4, 7, 10)', name='ck_med_allergies_onset'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_med_allergies_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_med_allergies')),
    sa.UniqueConstraint('patient_id', 'substance_key', name='uq_med_allergies_patient_substance')
    )
    with op.batch_alter_table('med_allergies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_allergies_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_med_allergies_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_allergies_substance'), ['substance'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_allergies_updated_at'), ['updated_at'], unique=False)

    op.create_table('med_corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('record_label', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("record_type IN ('history','medication','allergy','vaccination','result','provider')", name='ck_med_corrections_record_type'),
    sa.CheckConstraint("status IN ('open','resolved','declined','withdrawn')", name='ck_med_corrections_status'),
    sa.CheckConstraint('length(message) >= 1', name='ck_med_corrections_message'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_med_corrections_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_med_corrections'))
    )
    with op.batch_alter_table('med_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_corrections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_corrections_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_med_corrections_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index('ix_med_corrections_record', ['record_type', 'record_id'], unique=False)

    op.create_table('med_providers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('role_in_care', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('is_care_team', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('linked_provider_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='patient_entered', nullable=False),
    sa.Column('confirmed_by', sa.String(length=200), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('clinician','facility','pharmacy','lab','other')", name='ck_med_providers_kind'),
    sa.CheckConstraint("source IN ('patient_entered','clinician_confirmed')", name='ck_med_providers_source'),
    sa.CheckConstraint('length(name) >= 1', name='ck_med_providers_name'),
    sa.ForeignKeyConstraint(['linked_provider_id'], ['providers.id'], name=op.f('fk_med_providers_linked_provider_id_providers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_med_providers_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_med_providers')),
    sa.UniqueConstraint('patient_id', 'name_key', name='uq_med_providers_patient_name')
    )
    with op.batch_alter_table('med_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_providers_linked_provider_id'), ['linked_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_providers_name'), ['name'], unique=False)
        batch_op.create_index('ix_med_providers_patient_care_team', ['patient_id', 'is_care_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_providers_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_providers_updated_at'), ['updated_at'], unique=False)

    op.create_table('patient_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_sessions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_patient_sessions'))
    )
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_sessions_patient_id'), ['patient_id'], unique=False)

    op.create_table('privacy_settings',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('default_share_days', sa.Integer(), nullable=False),
    sa.Column('default_share_categories_json', sa.Text(), nullable=False),
    sa.Column('share_requires_my_approval', sa.Boolean(), nullable=False),
    sa.Column('notify_on_view', sa.Boolean(), nullable=False),
    sa.Column('allow_email', sa.Boolean(), nullable=False),
    sa.Column('allow_sms', sa.Boolean(), nullable=False),
    sa.Column('allow_phone_calls', sa.Boolean(), nullable=False),
    sa.Column('allow_appointment_reminders', sa.Boolean(), nullable=False),
    sa.Column('allow_marketing', sa.Boolean(), nullable=False),
    sa.Column('text_size', sa.String(length=10), nullable=False),
    sa.Column('high_contrast', sa.Boolean(), nullable=False),
    sa.Column('reduced_motion', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("text_size IN ('normal','large','xlarge')", name='ck_privacy_text_size'),
    sa.CheckConstraint('default_share_days >= 1 AND default_share_days <= 365', name='ck_privacy_share_days'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_privacy_settings_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('pk_privacy_settings'))
    )
    op.create_table('share_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('categories_json', sa.Text(), nullable=False),
    sa.Column('document_ids_json', sa.Text(), nullable=False),
    sa.Column('include_private', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('grant_days', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('grant_days > 0', name='ck_share_tokens_grant_days_pos'),
    sa.CheckConstraint('max_uses >= 1 AND use_count >= 0', name='ck_share_tokens_uses'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_share_tokens_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_tokens'))
    )
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_tokens_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('staff_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('front_desk', 'nurse', 'physician', 'admin')", name='ck_staff_users_role'),
    sa.CheckConstraint("role IN ('front_desk','nurse','physician','admin')", name='ck_staff_role'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_staff_users_provider_id_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users'))
    )
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_users_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index('ix_staff_users_provider_role', ['provider_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_users_role'), ['role'], unique=False)

    op.create_table('access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('categories_json', sa.Text(), nullable=False),
    sa.Column('document_ids_json', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','denied','expired')", name='ck_access_requests_status'),
    sa.CheckConstraint('duration_days > 0', name='ck_access_requests_duration_pos'),
    sa.CheckConstraint('duration_days >= 1', name='ck_access_requests_duration'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_access_requests_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_access_requests_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], name=op.f('fk_access_requests_staff_id_staff_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_requests'))
    )
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_access_requests_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_status'), ['status'], unique=False)

    op.create_table('appointment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("actor_type IN ('patient','staff','caregiver','system')", name='ck_appt_event_actor'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_events_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_events'))
    )
    with op.batch_alter_table('appointment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_events_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index('ix_appt_events_appt_ts', ['appointment_id', 'ts'], unique=False)

    op.create_table('document_blobs',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.CheckConstraint('length(data) > 0', name='ck_document_blobs_data_nonempty'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_blobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document_blobs'))
    )
    op.create_table('insurance_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('insurer_name', sa.String(length=200), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('member_id', sa.String(length=60), nullable=False),
    sa.Column('group_number', sa.String(length=60), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('policyholder_name', sa.String(length=200), nullable=False),
    sa.Column('policyholder_relationship', sa.String(length=20), nullable=False),
    sa.Column('policyholder_dob', sa.Date(), nullable=True),
    sa.Column('coverage_rank', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('deductible_annual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('out_of_pocket_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('copay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('coinsurance_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('insurer_phone', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_note', sa.String(length=300), nullable=True),
    sa.Column('card_front_document_id', sa.String(length=36), nullable=True),
    sa.Column('card_back_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("coverage_rank IN ('primary','secondary','tertiary')", name='ck_insurance_plan_rank'),
    sa.CheckConstraint("plan_type IN ('hmo','ppo','epo','pos','hdhp','medicare','medicaid','dental','vision','other')", name='ck_insurance_plan_type'),
    sa.CheckConstraint("policyholder_relationship IN ('self','spouse','parent','child','other')", name='ck_insurance_plan_relationship'),
    sa.CheckConstraint("verification_status IN ('entered','verified','failed')", name='ck_insurance_plan_verification'),
    sa.CheckConstraint('coinsurance_pct IS NULL OR (coinsurance_pct >= 0 AND coinsurance_pct <= 100)', name='ck_insurance_plan_coinsurance'),
    sa.CheckConstraint('copay_amount IS NULL OR copay_amount >= 0', name='ck_insurance_plan_copay'),
    sa.CheckConstraint('deductible_annual IS NULL OR deductible_annual >= 0', name='ck_insurance_plan_deductible'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= effective_date', name='ck_insurance_plan_dates'),
    sa.CheckConstraint('out_of_pocket_max IS NULL OR out_of_pocket_max >= 0', name='ck_insurance_plan_oop'),
    sa.ForeignKeyConstraint(['card_back_document_id'], ['documents.id'], name=op.f('fk_insurance_plans_card_back_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_front_document_id'], ['documents.id'], name=op.f('fk_insurance_plans_card_front_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_insurance_plans_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_plans')),
    sa.UniqueConstraint('patient_id', 'dedupe_key', name='uq_insurance_plan_dedupe')
    )
    with op.batch_alter_table('insurance_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_plans_card_back_document_id'), ['card_back_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_plans_card_front_document_id'), ['card_front_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_plans_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_plans_insurer_name'), ['insurer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_plans_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_insurance_plans_patient_rank', ['patient_id', 'coverage_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_plans_verification_status'), ['verification_status'], unique=False)

    op.create_table('med_history',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('relation', sa.String(length=60), nullable=True),
    sa.Column('facility_name', sa.String(length=200), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='patient_entered', nullable=False),
    sa.Column('confirmed_by', sa.String(length=200), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('condition','surgery','hospitalization','family_history')", name='ck_med_history_kind'),
    sa.CheckConstraint("source IN ('patient_entered','clinician_confirmed')", name='ck_med_history_source'),
    sa.CheckConstraint("status IN ('active','resolved','unknown')", name='ck_med_history_status'),
    sa.CheckConstraint('end_date IS NULL OR length(end_date) IN (4, 7, 10)', name='ck_med_history_end_date'),
    sa.CheckConstraint('length(title) >= 1', name='ck_med_history_title'),
    sa.CheckConstraint('start_date IS NULL OR length(start_date) IN (4, 7, 10)', name='ck_med_history_start_date'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_med_history_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['med_providers.id'], name=op.f('fk_med_history_provider_id_med_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_med_history'))
    )
    with op.batch_alter_table('med_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_history_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_med_history_patient_kind', ['patient_id', 'kind'], unique=False)
        batch_op.create_index('ix_med_history_patient_start', ['patient_id', 'start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_history_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_history_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_history_updated_at'), ['updated_at'], unique=False)

    op.create_table('med_medications',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('is_supplement', sa.Boolean(), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('prescriber_name', sa.String(length=200), nullable=True),
    sa.Column('prescriber_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='patient_entered', nullable=False),
    sa.Column('confirmed_by', sa.String(length=200), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('patient_entered','clinician_confirmed')", name='ck_med_medications_source'),
    sa.CheckConstraint("status IN ('active','past')", name='ck_med_medications_status'),
    sa.CheckConstraint('end_date IS NULL OR length(end_date) IN (4, 7, 10)', name='ck_med_medications_end_date'),
    sa.CheckConstraint('length(name) >= 1', name='ck_med_medications_name'),
    sa.CheckConstraint('start_date IS NULL OR length(start_date) IN (4, 7, 10)', name='ck_med_medications_start_date'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_med_medications_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescriber_id'], ['med_providers.id'], name=op.f('fk_med_medications_prescriber_id_med_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_med_medications'))
    )
    with op.batch_alter_table('med_medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_medications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_medications_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_med_medications_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_medications_prescriber_id'), ['prescriber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_medications_updated_at'), ['updated_at'], unique=False)

    op.create_table('med_results',
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('test_key', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('value_num', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value_text', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('ref_low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ref_high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ref_text', sa.String(length=200), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='patient_entered', nullable=False),
    sa.Column('confirmed_by', sa.String(length=200), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('lab','imaging','other')", name='ck_med_results_category'),
    sa.CheckConstraint("source IN ('patient_entered','clinician_confirmed')", name='ck_med_results_source'),
    sa.CheckConstraint('length(test_name) >= 1', name='ck_med_results_test_name'),
    sa.CheckConstraint('ref_low IS NULL OR ref_high IS NULL OR ref_low <= ref_high', name='ck_med_results_ref_order'),
    sa.CheckConstraint('value_num IS NOT NULL OR value_text IS NOT NULL', name='ck_med_results_has_value'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_med_results_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_med_results_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['med_providers.id'], name=op.f('fk_med_results_provider_id_med_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_med_results'))
    )
    with op.batch_alter_table('med_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_results_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_med_results_patient_date', ['patient_id', 'result_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_results_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_med_results_patient_series', ['patient_id', 'test_key', 'result_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_results_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_results_test_name'), ['test_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_results_updated_at'), ['updated_at'], unique=False)

    op.create_table('med_vaccinations',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('date_given', sa.String(length=10), nullable=True),
    sa.Column('dose_number', sa.Integer(), nullable=True),
    sa.Column('administered_by', sa.String(length=200), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='patient_entered', nullable=False),
    sa.Column('confirmed_by', sa.String(length=200), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('vaccine','screening','preventive_care')", name='ck_med_vaccinations_kind'),
    sa.CheckConstraint("source IN ('patient_entered','clinician_confirmed')", name='ck_med_vaccinations_source'),
    sa.CheckConstraint("status IN ('completed','scheduled','declined','unknown')", name='ck_med_vaccinations_status'),
    sa.CheckConstraint('date_given IS NULL OR length(date_given) IN (4, 7, 10)', name='ck_med_vaccinations_date_given'),
    sa.CheckConstraint('dose_number IS NULL OR (dose_number >= 1 AND dose_number <= 20)', name='ck_med_vaccinations_dose'),
    sa.CheckConstraint('length(name) >= 1', name='ck_med_vaccinations_name'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_med_vaccinations_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['med_providers.id'], name=op.f('fk_med_vaccinations_provider_id_med_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_med_vaccinations'))
    )
    with op.batch_alter_table('med_vaccinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_vaccinations_name'), ['name'], unique=False)
        batch_op.create_index('ix_med_vaccinations_patient_due', ['patient_id', 'next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_vaccinations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_vaccinations_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_vaccinations_updated_at'), ['updated_at'], unique=False)

    op.create_table('staff_patient_confirmations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_staff_patient_confirmations_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], name=op.f('fk_staff_patient_confirmations_staff_id_staff_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_patient_confirmations')),
    sa.UniqueConstraint('staff_id', 'patient_id', name='uq_staff_patient_confirm')
    )
    with op.batch_alter_table('staff_patient_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_patient_confirmations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_patient_confirmations_staff_id'), ['staff_id'], unique=False)

    op.create_table('staff_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], name=op.f('fk_staff_sessions_staff_id_staff_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_staff_sessions'))
    )
    with op.batch_alter_table('staff_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_sessions_staff_id'), ['staff_id'], unique=False)

    op.create_table('billing_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('claim_key', sa.String(length=100), nullable=False),
    sa.Column('insurer_name', sa.String(length=200), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('service_description', sa.String(length=300), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insurer_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deductible', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('copay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('coinsurance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('patient_responsibility', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('denial_reason', sa.String(length=300), nullable=True),
    sa.Column('eob_document_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('submitted','processing','paid','partially_denied','denied','appealed')", name='ck_billing_claim_status'),
    sa.CheckConstraint('allowed_amount IS NULL OR allowed_amount >= 0', name='ck_billing_claim_allowed'),
    sa.CheckConstraint('billed_amount >= 0', name='ck_billing_claim_billed'),
    sa.CheckConstraint('coinsurance IS NULL OR coinsurance >= 0', name='ck_billing_claim_coinsurance'),
    sa.CheckConstraint('copay IS NULL OR copay >= 0', name='ck_billing_claim_copay'),
    sa.CheckConstraint('deductible IS NULL OR deductible >= 0', name='ck_billing_claim_deductible'),
    sa.CheckConstraint('insurer_paid IS NULL OR insurer_paid >= 0', name='ck_billing_claim_paid'),
    sa.CheckConstraint('patient_responsibility IS NULL OR patient_responsibility >= 0', name='ck_billing_claim_resp'),
    sa.ForeignKeyConstraint(['eob_document_id'], ['documents.id'], name=op.f('fk_billing_claims_eob_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_billing_claims_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], name=op.f('fk_billing_claims_plan_id_insurance_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_claims')),
    sa.UniqueConstraint('patient_id', 'claim_key', name='uq_billing_claim_dedupe')
    )
    with op.batch_alter_table('billing_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_claims_claim_number'), ['claim_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_claims_eob_document_id'), ['eob_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_claims_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_claims_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_claims_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_claims_service_date'), ['service_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_claims_status'), ['status'], unique=False)

    op.create_table('share_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=10), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('include_private', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('via', sa.String(length=20), nullable=False),
    sa.Column('access_request_id', sa.String(length=36), nullable=True),
    sa.Column('token_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(scope_type = 'document' AND document_id IS NOT NULL) OR (scope_type = 'category' AND category IS NOT NULL)", name='ck_share_grants_target'),
    sa.CheckConstraint("scope_type IN ('document','category')", name='ck_share_grants_scope'),
    sa.CheckConstraint("via IN ('patient', 'access_request', 'token')", name='ck_share_grants_via'),
    sa.ForeignKeyConstraint(['access_request_id'], ['access_requests.id'], name=op.f('fk_share_grants_access_request_id_access_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_share_grants_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_share_grants_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_share_grants_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['share_tokens.id'], name=op.f('fk_share_grants_token_id_share_tokens'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_grants'))
    )
    with op.batch_alter_table('share_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_grants_access_request_id'), ['access_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_grants_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_share_grants_document', ['document_id', 'provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_grants_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_share_grants_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_share_grants_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_share_grants_lookup', ['patient_id', 'provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_grants_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_grants_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_grants_token_id'), ['token_id'], unique=False)

    op.create_table('billing_bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=80), nullable=True),
    sa.Column('dedupe_key', sa.String(length=400), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('last_reminder_key', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("match_status IN ('unmatched','matched')", name='ck_billing_bill_match'),
    sa.CheckConstraint("status IN ('unpaid','partially_paid','paid','in_dispute','void')", name='ck_billing_bill_status'),
    sa.CheckConstraint('billed_amount >= 0 AND amount_due >= 0', name='ck_billing_bill_amounts'),
    sa.ForeignKeyConstraint(['claim_id'], ['billing_claims.id'], name=op.f('fk_billing_bills_claim_id_billing_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_billing_bills_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], name=op.f('fk_billing_bills_plan_id_insurance_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_bills')),
    sa.UniqueConstraint('claim_id', name='uq_billing_bill_claim'),
    sa.UniqueConstraint('patient_id', 'dedupe_key', name='uq_billing_bill_dedupe')
    )
    with op.batch_alter_table('billing_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_bills_due_date'), ['due_date'], unique=False)
        batch_op.create_index('ix_billing_bills_patient_due', ['patient_id', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_bills_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_billing_bills_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_bills_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_bills_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_bills_service_date'), ['service_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_bills_status'), ['status'], unique=False)

    op.create_table('billing_disputes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('disputed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_before', sa.String(length=20), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason_code IN ('amount_wrong','duplicate_charge','insurance_not_applied','service_not_received','claim_denied','other')", name='ck_billing_dispute_reason'),
    sa.CheckConstraint("status IN ('open','resolved','withdrawn')", name='ck_billing_dispute_status'),
    sa.ForeignKeyConstraint(['bill_id'], ['billing_bills.id'], name=op.f('fk_billing_disputes_bill_id_billing_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_billing_disputes_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_disputes'))
    )
    with op.batch_alter_table('billing_disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_disputes_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_disputes_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_disputes_status'), ['status'], unique=False)
        batch_op.create_index('uq_billing_dispute_open_per_bill', ['bill_id'], unique=True, sqlite_where=sa.text("status = 'open'"), postgresql_where=sa.text("status = 'open'"))

    op.create_table('billing_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confirmation_number', sa.String(length=80), nullable=True),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('receipt_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('card','check','cash','bank_transfer','hsa_fsa','other')", name='ck_billing_payment_method'),
    sa.CheckConstraint('amount > 0', name='ck_billing_payment_amount'),
    sa.ForeignKeyConstraint(['bill_id'], ['billing_bills.id'], name=op.f('fk_billing_payments_bill_id_billing_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_billing_payments_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_document_id'], ['documents.id'], name=op.f('fk_billing_payments_receipt_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_payments')),
    sa.UniqueConstraint('bill_id', 'confirmation_number', name='uq_billing_payment_confirmation'),
    sa.UniqueConstraint('patient_id', 'receipt_number', name='uq_billing_payment_receipt')
    )
    with op.batch_alter_table('billing_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_payments_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index('ix_billing_payments_bill_paid', ['bill_id', 'paid_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_payments_paid_on'), ['paid_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_payments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_payments_receipt_document_id'), ['receipt_document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_payments_receipt_document_id'))
        batch_op.drop_index(batch_op.f('ix_billing_payments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_billing_payments_paid_on'))
        batch_op.drop_index('ix_billing_payments_bill_paid')
        batch_op.drop_index(batch_op.f('ix_billing_payments_bill_id'))

    op.drop_table('billing_payments')
    with op.batch_alter_table('billing_disputes', schema=None) as batch_op:
        batch_op.drop_index('uq_billing_dispute_open_per_bill', sqlite_where=sa.text("status = 'open'"), postgresql_where=sa.text("status = 'open'"))
        batch_op.drop_index(batch_op.f('ix_billing_disputes_status'))
        batch_op.drop_index(batch_op.f('ix_billing_disputes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_billing_disputes_bill_id'))

    op.drop_table('billing_disputes')
    with op.batch_alter_table('billing_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_bills_status'))
        batch_op.drop_index(batch_op.f('ix_billing_bills_service_date'))
        batch_op.drop_index(batch_op.f('ix_billing_bills_provider_name'))
        batch_op.drop_index(batch_op.f('ix_billing_bills_plan_id'))
        batch_op.drop_index('ix_billing_bills_patient_status')
        batch_op.drop_index(batch_op.f('ix_billing_bills_patient_id'))
        batch_op.drop_index('ix_billing_bills_patient_due')
        batch_op.drop_index(batch_op.f('ix_billing_bills_due_date'))

    op.drop_table('billing_bills')
    with op.batch_alter_table('share_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_grants_token_id'))
        batch_op.drop_index(batch_op.f('ix_share_grants_provider_id'))
        batch_op.drop_index(batch_op.f('ix_share_grants_patient_id'))
        batch_op.drop_index('ix_share_grants_lookup')
        batch_op.drop_index('ix_share_grants_expires_at')
        batch_op.drop_index('ix_share_grants_expires')
        batch_op.drop_index(batch_op.f('ix_share_grants_document_id'))
        batch_op.drop_index('ix_share_grants_document')
        batch_op.drop_index(batch_op.f('ix_share_grants_created_at'))
        batch_op.drop_index(batch_op.f('ix_share_grants_access_request_id'))

    op.drop_table('share_grants')
    with op.batch_alter_table('billing_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_claims_status'))
        batch_op.drop_index(batch_op.f('ix_billing_claims_service_date'))
        batch_op.drop_index(batch_op.f('ix_billing_claims_provider_name'))
        batch_op.drop_index(batch_op.f('ix_billing_claims_plan_id'))
        batch_op.drop_index(batch_op.f('ix_billing_claims_patient_id'))
        batch_op.drop_index(batch_op.f('ix_billing_claims_eob_document_id'))
        batch_op.drop_index(batch_op.f('ix_billing_claims_claim_number'))

    op.drop_table('billing_claims')
    with op.batch_alter_table('staff_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_sessions_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_sessions_expires_at'))

    op.drop_table('staff_sessions')
    with op.batch_alter_table('staff_patient_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_patient_confirmations_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_patient_confirmations_patient_id'))

    op.drop_table('staff_patient_confirmations')
    with op.batch_alter_table('med_vaccinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_vaccinations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_med_vaccinations_provider_id'))
        batch_op.drop_index(batch_op.f('ix_med_vaccinations_patient_id'))
        batch_op.drop_index('ix_med_vaccinations_patient_due')
        batch_op.drop_index(batch_op.f('ix_med_vaccinations_name'))

    op.drop_table('med_vaccinations')
    with op.batch_alter_table('med_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_results_updated_at'))
        batch_op.drop_index(batch_op.f('ix_med_results_test_name'))
        batch_op.drop_index(batch_op.f('ix_med_results_provider_id'))
        batch_op.drop_index('ix_med_results_patient_series')
        batch_op.drop_index(batch_op.f('ix_med_results_patient_id'))
        batch_op.drop_index('ix_med_results_patient_date')
        batch_op.drop_index(batch_op.f('ix_med_results_document_id'))

    op.drop_table('med_results')
    with op.batch_alter_table('med_medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_medications_updated_at'))
        batch_op.drop_index(batch_op.f('ix_med_medications_prescriber_id'))
        batch_op.drop_index('ix_med_medications_patient_status')
        batch_op.drop_index(batch_op.f('ix_med_medications_patient_id'))
        batch_op.drop_index(batch_op.f('ix_med_medications_name'))

    op.drop_table('med_medications')
    with op.batch_alter_table('med_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_history_updated_at'))
        batch_op.drop_index(batch_op.f('ix_med_history_title'))
        batch_op.drop_index(batch_op.f('ix_med_history_provider_id'))
        batch_op.drop_index('ix_med_history_patient_start')
        batch_op.drop_index('ix_med_history_patient_kind')
        batch_op.drop_index(batch_op.f('ix_med_history_patient_id'))

    op.drop_table('med_history')
    with op.batch_alter_table('insurance_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_plans_verification_status'))
        batch_op.drop_index('ix_insurance_plans_patient_rank')
        batch_op.drop_index(batch_op.f('ix_insurance_plans_patient_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_plans_insurer_name'))
        batch_op.drop_index(batch_op.f('ix_insurance_plans_effective_date'))
        batch_op.drop_index(batch_op.f('ix_insurance_plans_card_front_document_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_plans_card_back_document_id'))

    op.drop_table('insurance_plans')
    op.drop_table('document_blobs')
    with op.batch_alter_table('appointment_events', schema=None) as batch_op:
        batch_op.drop_index('ix_appt_events_appt_ts')
        batch_op.drop_index(batch_op.f('ix_appointment_events_appointment_id'))

    op.drop_table('appointment_events')
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_requests_status'))
        batch_op.drop_index(batch_op.f('ix_access_requests_staff_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_provider_id'))
        batch_op.drop_index('ix_access_requests_patient_status')
        batch_op.drop_index(batch_op.f('ix_access_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_created_at'))

    op.drop_table('access_requests')
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_users_role'))
        batch_op.drop_index('ix_staff_users_provider_role')
        batch_op.drop_index(batch_op.f('ix_staff_users_provider_id'))
        batch_op.drop_index(batch_op.f('ix_staff_users_name'))
        batch_op.drop_index(batch_op.f('ix_staff_users_email'))

    op.drop_table('staff_users')
    with op.batch_alter_table('share_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_share_tokens_patient_id'))
        batch_op.drop_index(batch_op.f('ix_share_tokens_expires_at'))

    op.drop_table('share_tokens')
    op.drop_table('privacy_settings')
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_sessions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_sessions_expires_at'))

    op.drop_table('patient_sessions')
    with op.batch_alter_table('med_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_providers_updated_at'))
        batch_op.drop_index(batch_op.f('ix_med_providers_patient_id'))
        batch_op.drop_index('ix_med_providers_patient_care_team')
        batch_op.drop_index(batch_op.f('ix_med_providers_name'))
        batch_op.drop_index(batch_op.f('ix_med_providers_linked_provider_id'))

    op.drop_table('med_providers')
    with op.batch_alter_table('med_corrections', schema=None) as batch_op:
        batch_op.drop_index('ix_med_corrections_record')
        batch_op.drop_index('ix_med_corrections_patient_status')
        batch_op.drop_index(batch_op.f('ix_med_corrections_patient_id'))
        batch_op.drop_index(batch_op.f('ix_med_corrections_created_at'))

    op.drop_table('med_corrections')
    with op.batch_alter_table('med_allergies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_allergies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_med_allergies_substance'))
        batch_op.drop_index('ix_med_allergies_patient_status')
        batch_op.drop_index(batch_op.f('ix_med_allergies_patient_id'))

    op.drop_table('med_allergies')
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_patient_id'))

    op.drop_table('emergency_contacts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('uq_documents_patient_sha_active', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('uq_documents_patient_sha256_live', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_patient_id'))
        batch_op.drop_index('ix_documents_patient_created')
        batch_op.drop_index(batch_op.f('ix_documents_name'))
        batch_op.drop_index(batch_op.f('ix_documents_mime_type'))
        batch_op.drop_index(batch_op.f('ix_documents_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_category'))

    op.drop_table('documents')
    with op.batch_alter_table('dependent_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependent_profiles_guardian_patient_id'))

    op.drop_table('dependent_profiles')
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletion_requests_status'))
        batch_op.drop_index('ix_deletion_requests_patient_status')
        batch_op.drop_index(batch_op.f('ix_deletion_requests_patient_id'))

    op.drop_table('deletion_requests')
    with op.batch_alter_table('connected_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connected_apps_patient_id'))
        batch_op.drop_index('ix_connected_apps_patient')

    op.drop_table('connected_apps')
    with op.batch_alter_table('caregiver_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caregiver_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_caregiver_sessions_caregiver_id'))

    op.drop_table('caregiver_sessions')
    with op.batch_alter_table('caregiver_links', schema=None) as batch_op:
        batch_op.drop_index('ix_caregiver_links_patient_status')
        batch_op.drop_index(batch_op.f('ix_caregiver_links_patient_id'))
        batch_op.drop_index(batch_op.f('ix_caregiver_links_expires_at'))
        batch_op.drop_index('ix_caregiver_links_email')
        batch_op.drop_index(batch_op.f('ix_caregiver_links_caregiver_id'))

    op.drop_table('caregiver_links')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_updated_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index('ix_appointments_scheduled_for')
        batch_op.drop_index('ix_appointments_provider_status')
        batch_op.drop_index(batch_op.f('ix_appointments_provider_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusted_devices_expires_at'))
        batch_op.drop_index('ix_trusted_account')

    op.drop_table('trusted_devices')
    with op.batch_alter_table('share_token_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_share_token_attempts_key_ts')

    op.drop_table('share_token_attempts')
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_log_created_at'))

    op.drop_table('reminder_log')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index('ix_providers_name')

    op.drop_table('providers')
    with op.batch_alter_table('pending_signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_signups_expires_at'))
        batch_op.drop_index(batch_op.f('ix_pending_signups_email'))

    op.drop_table('pending_signups')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_legal_name')
        batch_op.drop_index(batch_op.f('ix_patients_email'))
        batch_op.drop_index('ix_patients_dob')

    op.drop_table('patients')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_key_created')
        batch_op.drop_index('ix_otp_ip_created')
        batch_op.drop_index(batch_op.f('ix_otp_codes_email'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_created_at'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_challenge_hash'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_account_id'))

    op.drop_table('otp_codes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_ts'))
        batch_op.drop_index('ix_notifications_recipient_unread')
        batch_op.drop_index('ix_notifications_recipient_ts')
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_prefs_recipient_id'))

    op.drop_table('notification_prefs')
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.drop_index('ix_loginfail_ip_ts')
        batch_op.drop_index('ix_loginfail_email_ts')

    op.drop_table('login_failures')
    with op.batch_alter_table('caregiver_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caregiver_accounts_email'))

    op.drop_table('caregiver_accounts')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index('ix_audit_log_patient_ts')
        batch_op.drop_index(batch_op.f('ix_audit_log_patient_id'))
        batch_op.drop_index('ix_audit_log_actor')
        batch_op.drop_index('ix_audit_log_action')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
