"""DB-level guarantees: append-only audit_log triggers, PostgreSQL blob storage tuning.

Hand-written (autogenerate cannot see triggers). Safe to re-run: all installers are idempotent.
Keep this revision AFTER the autogenerated schema revision(s).

Revision ID: 0002
Revises: 0001
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _expression_indexes():
    """Functional indexes (e.g. lower(email)) - autogenerate on SQLite cannot see/render these."""
    from app.db_ops.policies import INDEXES

    return [(t, name, cols, uniq) for t, name, cols, uniq in INDEXES if any("(" in c for c in cols)]


def upgrade() -> None:
    from sqlalchemy import inspect

    from app.db_ops.triggers import ensure_db_objects

    bind = op.get_bind()
    insp = inspect(bind)
    for table, name, cols, unique in _expression_indexes():
        if insp.has_table(table):
            op.execute(f"CREATE {'UNIQUE ' if unique else ''}INDEX IF NOT EXISTS {name} "
                       f"ON {table} ({', '.join(cols)})")
    ensure_db_objects(bind)


def downgrade() -> None:
    bind = op.get_bind()
    for table, name, _cols, _u in _expression_indexes():
        op.execute(f"DROP INDEX IF EXISTS {name}")
    if bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_change ON audit_log")
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS audit_log_immutable()")
    else:
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_update")
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_delete")
